### PR TITLE
Wifi Menu

### PR DESCRIPTION
**Pull request by WalnutFox**
This is a wifi menu that i have added to octodash, i can only confirm that it works in the dev environment. i will update this when i get a chance to test on my rpi. 

the only problem with this at the moment is that it requires root access and a keyboard.

### CODE REVIEW

**Comment by WalnutFox** [comment]
for this to work without password prompt i recommend setting iwlist, wpa_cli and rfkill are set to nopasswd in the sudoers file.

**Comment by WalnutFox** [comment]
I have confirmed that this does indeed work on the raspberry pi, I will be adding a bit more functionality to the wifi menu as well to tell you the ip address.

**Comment by WalnutFox** [comment]
I have added IP and SSID to the wifi-menu that gets updated after connecting. added dhclient release and renew to allow the pi to get a new ip address.

recommended to add dhclient to visudo as well.

**Comment by WalnutFox** [comment]
If anyone knows how to setup popups to let user know delay reason, let me know. next commit is my attempt but it is missing stuff to get it to work.

**Comment by UnchartedBull** [comment]
Thanks for you contribution! :) Just had a quick brush over this:

- If I don't enable sudo it would just hang with no way of exiting other than entering the sudo password on the CLI
- Not entirely a fan of the CLI usage in the actual frontend
- Doesn't work an a Mac (not a huge issue, but makes it a little harder to test for me at least)

Here are my 2 cents:

- It would be great if all the stuff that needs node and / or CLI commands could be pushed over to the electron side of things
- I stumbled upon these two libraries: https://www.npmjs.com/package/node-wifi and https://www.npmjs.com/package/ip which do seem to achieve the exact same thing without the need for sudo (at least from what I can tell from their READMEs)

I know this is asking quite a lot (and I'm happy to help here if you want me to), but it would be great if we could try the mentioned libraries and check whether they may be able to achieve the functionality without needing privileged rights. They should be encapsulated in their own wrapper similar to how the bonjour implementation is done (https://github.com/UnchartedBull/OctoDash/blob/master/helper/discover.js). Communication would be done via the IPC, this would also keep the logic encapsulated in its own component and away from the settings component so it could be easily reused in other screens.

**Comment by UnchartedBull** [comment]
Oh and if you want to send a notification use the NotificationService :)

**Comment by WalnutFox** [comment]
i'll be honest i dont really have a good understanding of using angular or electron and most of the code is borrowed then change to get it to work. the original source for the code is mozilla gateway for iot. 

with my current knowledge i dont know how to keep things separate between angular and electron.

i do know that on linux however you cannot run those command and use them without using sudo in front of them.

**Pull request closed without merging**
