### PR TITLE
replace html logo by svg and package fonts

### PR DESCRIPTION
**Pull request by pciavald**
This PR fixes octodash's logo on the main-menu, replacing the hard-coded HTML version of the logo by a SVG logo.

It also packages the fonts as OctoDash may not always be connected to internet, and getting the fonts from google in index.html may then not always work.

Note: may break themes

### CODE REVIEW

**Comment by pciavald** [comment]
This is ready to merge

**Review by UnchartedBull — APPROVED** [review]

**Comment by UnchartedBull** [comment]
The svg logo isn't working. Going to revert to the normal text-based logo, the local fonts are a nice addition though. It also doesn't scale well on different resolutions.

image

**Comment by pciavald** [comment]
@UnchartedBull Ooops, i did not see that! Can i still try to fix it?

**Comment by UnchartedBull** [comment]
Sure feel free to create another PR for that.

**Pull request merged**
