### PR TITLE
--allow-releaseinfo-change

### PR DESCRIPTION
**Pull request by jneilliii**
possible fix for recent install errors, #2206, #2207

### CODE REVIEW

**Comment by UnchartedBull** [comment]
Thanks for leading all the discussions in the issues! Was kinda busy the last couple of weeks and didn't really had time to check in. 

Just one question: Does this have any side implications, i.e. are there users that might be locked onto a different release-info?

**Comment by UnchartedBull** [comment]
Just searched around the internet on how to handle that. Information seems fairly sparse, but I was able to find this:

```
--allow-releaseinfo-change
  Allow the update command to continue downloading data from a repository which changed its information of the release 
  contained in the repository indicating e.g a new major release. APT will fail at the update command for such 
  repositories until the change is confirmed to ensure the user is prepared for the change. 
  See also apt-secure(8) for details on the concept and configuration.
```

So this would indicate, that this shouldn't be done by some script, that is being downloaded from the internet. I thought that maybe pinning the issue for a couple of weeks and adding an entry to the troubleshooting guide might also work?

**Comment by jneilliii** [comment]
From what we've seen it appears to only error out with apt-get, and not with just apt, so maybe that is an option. only issue is that it complains about not having a good CLI implementation, but from what I've seen with the CustOpiZer fixes with this implemented there were no bad side effects. I totally get not wanting to add it, but just trying to eliminate that from your support overhead, because it will continue...

**Comment by UnchartedBull** [comment]
Yeah I totally get that with the support request. Those are usually easy to handle, but I'm afraid of maybe a ticket opening up that basically says: "hey guys, you crashed my linux installation. Thank you very much."

Interesting finding with `apt` and `apt-get` though. The script is already using `apt` though, so this might not apply in this case?

Another option would be to check for that error message and directly tell the user: Hey this happened, here is how to fix that. Might need to investigate this a little.

**Comment by jneilliii** [comment]
Yeah, a sane error is definitely something to consider and I get your point. Guysoft is struggling with the same thing and I believe wants to see if this is an upstream issue with the pi-gen project.

**Comment by jneilliii** [comment]
from what I understand from the linked issues, some people have mentioned just running the sudo apt update command ahead of the install script is enough to allow the install script to work, so maybe catch the error and re-run is an option.

**Comment by UnchartedBull** [comment]
Hi, I updated your branch with the error message (hope that is ok). It now looks like this if apt throws an error:

Screenshot 2021-09-15 at 13 30 01

This can be merged if you're also ok with the changes :)

**Comment by jneilliii** [comment]
No problem on my end.

**Review by UnchartedBull — APPROVED** [review]

**Review by UnchartedBull — APPROVED** [review]

**Pull request merged**
