### PR TITLE
New Object SVG

### PR DESCRIPTION
**Pull request by thisiskeithb**
Something a little less....TH3D.

This PR replaces Object.svg:

### Current:
image

### Proposed:
image

["3d modeling" by Template, TH / the Noun Project
](https://thenounproject.com/paisurangkana/collection/3d-printing-outline/?i=2823293
)
License: [Creative Commons CCBY](https://creativecommons.org/licenses/by/3.0/us/legalcode).

### CODE REVIEW

**Comment by UnchartedBull** [comment]
Looks good. Didn‘t know the TH3D icon. Could you be so kind and replace the credits in the icon.txt file? Just replace the one from the old logo with the new one, after that small change this can be merged :)

**Comment by thisiskeithb** [comment]
I didn't find the old icon credit, but `icon.txt` has been updated.

**Comment by thisiskeithb** [comment]
@UnchartedBull: I suppose the screenshot below from the readme will need to be updated as well. Need a PR for that?

image

**Comment by UnchartedBull** [comment]
I can do that once I‘m ready with the next version. Thanks for the icon!

**Pull request merged**
