### PR TITLE
Add temperature controls to main menu

### PR DESCRIPTION
**Pull request by harleyg321**
Set Hotend Temperature
**Features Added**
This allows hotend and heatbed temperatures to be set from the main menu by clicking on their status icon/temperature.

While this could be managed from the control menu, I like having the preheat and cooldown buttons on there to set both hotend and heatbed temperatures. This allows control of each individually from the main menu, for example to set just the hotend temperature to remove the filament without also heating up the bed.

**Potential Improvements**
To save having to increment up from 0, I've set a default starting value of 200 for the hotend and 60 for the heatbed. This could be something retrieved from config to let users set their own default value.

This only adds the ability to adjust temperatures. It would make sense to also allow fan speed control in the same way. However I couldn't see an easy way already implemented to set fan speed so I've added temperature controls for now.

### CODE REVIEW

**Comment by UnchartedBull** [comment]
Looks great. Code also looks fine on first inspection. I'll add the config part during the next week and will merge after that. Thank you!

**Comment by harleyg321** [comment]
The ability to set fan speed probably isn't that useful, but for completeness I've also added it. I've used the printer status executeGCode function to issue an M106 Sxxx command to set the speed.

**Comment by UnchartedBull** [comment]
I somehow messed up this PR. I'm new to accepting PR's from other contributors, so bear with me. I somehow created a new branch by accident (https://github.com/UnchartedBull/OctoDash/tree/harleyg321-feature/temp_control) to which I pushed my proposed changes. Please have a look there and let me know, whether you're fine with them. I will also add the config part to this branch as well.

Let men know, whether we should merge this branch to your repo first, or whether we should directly merge into master from there.

**Comment by harleyg321** [comment]
Changes look good, I guess merging from that feature branch directly into master is probably easiest.

**Comment by UnchartedBull** [comment]
Ok then this will be merged in #523. Please have a look at the latest changes, once you're happy just comment on the other PR, after that I'll merge it then :)

**Pull request closed without merging**
